#ifndef WINDEPENDENCIESSCANNER_GLOBAL_H
#define WINDEPENDENCIESSCANNER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(WINDEPENDENCIESSCANNER_LIBRARY)
#  define WINDEPENDENCIESSCANNERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define WINDEPENDENCIESSCANNERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // WINDEPENDENCIESSCANNER_GLOBAL_H
