#!/bin/sh
#
# Copyright (c) 2009 The Chromium Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# Run the cron job immediately to perform repository configuration.
nohup sh /etc/cron.daily/google-chrome > /dev/null 2>&1 &
