#!/bin/bash

APPS=$BASH_ARRAY_APPLICATIONS

for app in "${APPS[@]}"
do

    SRC_FILE="$TARGET_DIR/$app.sh"
    rm "/usr/share/applications/$app.desktop"

    if [ -e /usr/bin/"${app,,}" ]; then
        rm /usr/bin/"${app,,}"
        echo "Remove ${app,,}"
    fi
done
