#
# Copyright (C) 2018-2020 QuasarApp.
# Distributed under the lgplv3 software license, see the accompanying
# Everyone is permitted to copy and distribute verbatim copies
# of this license document, but changing it is not allowed.
#

name: cqtdeployer # you probably want to 'snapcraft register <name>'
version: '1.4.0.2' # just for humans, typically '1.2+git' or '1.3.2'
summary: deploy your qt projects # 79 char long summary
description: |
  Console app for deploy qt libs.
  Key differences of this program
  Performance-this program deploys the application several times faster (up to 10 seconds)
  Flexibility-this application has flags that will help you configure the deployment as you need and your project

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
base: core18

apps:
  cqtdeployer:
    command: desktop-launch $SNAP/cqtdeployer.sh
    plugs: [home, removable-media, process-control]

  cqt:
    command: desktop-launch $SNAP/cqt.sh
    plugs: [home, removable-media, process-control]

parts:
  cqtdeployer:
    # See 'snapcraft plugins'

    plugin: dump
    source: QIFData/packages/cqtdeployer.1_4/data/1.4

    stage-packages:
      - libfreetype6
      - libpng16-16

    after: [cqtdeployer-wrapper]

  qif:
    plugin: dump
    source: QIFData/packages/QIF/data/

    override-stage: |
      snapcraftctl stage
      chmod 777 -R "$SNAPCRAFT_STAGE/QIF"

  cqtdeployer-wrapper:
    plugin: dump
    source: QuasarAppLib/Etalons/snap/wrapper
